# generic rules

%.runtestsuite : %.atestsuite
	$(SDF_TOOLS)/bin/parse-unit --no-heuristic-filters -i $< -p $(PARSE_UNIT_PTABLE) --verbose 1 -o /dev/null

%.atestsuite : %.testsuite
	$(SDF_TOOLS)/bin/parse-parse-testsuite  -i $< -o $@

# %.jasfix : %.java $(prefix)/share/sdf/java-front/Java.tbl
#	sglr -2lv -p $(prefix)/share/sdf/java-front/Java.tbl -i $< -o $@

