#!/bin/sh

rm -f config.cache config.log acconfig.h aclocal.m4

touch README
touch NEWS

autoxt
aclocal -I .
autoconf -f --warnings=all
automake -a -c -f  --warnings=all  --warnings=no-portability

#autoreconf --include=. --warnings=all --warnings=no-portability
